//infinitivo   pasado,   participio,    3er p,	    gerundio,    significado			significado extendido
var v= [
	["hit",		"hit", 		"hit", 		"hits", 	"hitting", 	"golpear/pegar",			""],
	//["become", 	"became", 	"became", 	"becomes", 	"becoming", 	"convertir/convertirse/volverse",	""],
	["fit",		"fitted/fit",	"fitted/fit",	"fits",		"fitting",	"ajustar/caber/adaptar/encajar",	"to be the right shape or size for someone or something"],
	["split",	"split", 	"split", 	"splits", 	"splitting", 	"dividir/apartar/separar/partir",	""],
	["let", 	"let", 		"let", 		"lets", 	"letting", 	"dejar/permitir",			""],
	["set",		"set",		"set",		"sets",		"setting",	"establecer/ajustar/fijar",		""],
	["spread",	"spread",	"spread",	"spreads",	"spreadign",	"difundir/esparcir/propagar/extender",	""],
	["put",		"put",		"put",		"puts",		"putting",	"poner",				""],
	["cut",		"cut",		"cut",		"cuts",		"cutting",	"cortar",				""],
	["shut",	"shut",		"shut",		"shuts",	"shutting",	"cerrar",				""],
	["thrust",	"thrust",	"thrust",	"thrusts",	"thrusting",	"empujar/introducir/impulsar/clavar",	"to push suddenly and strongly, Meter bruscamente, Abrir camino, Empujón, empuje del cohete o un empuje repentino, a menudo con gran fuerza"],
	["hurt",	"hurt",		"hurt",		"hurts",	"hurting",	"herir",				""],
	["burst",	"burst",	"burst",	"bursts",	"bursting",	"estallar/reventar/irrumpir",		""],
	["cast",	"cast",		"cast",		"casts",	"casting",	"emitir/transmitir/lanzar/arrojar",	"Lanzar un hechizo, Pasar a alguien algo(n)"],
	["broadcast",	"broadcast",	"broadcast",	"broadcasts",	"broadcasting",	"transmitir/emitir/difundir",		""],
	["forecast",	"forecast",	"forecast",	"forecasts",	"forecasting",	"pronosticar/prever/preever/predecir",	""],
	["cost",	"costed/cost",	"costed/cost",	"costs",	"costing",	"costar",				""],
	["beat",	"beat/beaten",	"beat/beaten",	"beats",	"beating",	"golpear/pegar/vencer/superar/latir",	""],
	["sweat",	"sweat/sweated","sweat/sweated","sweats",	"sweating",	"sudar",				""],
	["bet",		"betted/bet",	"betted/bet",	"bets",		"betting",	"apostar",				""],
	["wet",		"wetted/wet",	"wetted/wet",	"wets",		"wetting",	"mojar/humedecer",			""],
	["bid",		"bid/bade/bidden","bid/bade/bidden","bids/bid",	"bidding", 	"pujar/ofrecer",			"Ofrecer en una subasta"],
	["rid",		"ridded/rid", 	"ridded/rid",	"rids",		"ridding",	"eliminar/liberar/deshacerse/deshacer",	""],
	["slit",	"slitted/slit", "slitted/slit", "slits", 	"slitting",	"cortar/rajar/degollar",		""],
	["quit",	"quitted/quit", "quitted/quit", "quits", 	"quitting", 	"dejar/abandonar/renunciar/dimitir",	""],
	///Group 2
	["keep",	"kept",		"kept",		"keeps",	"keeping",	"mantener/retener",			""],
	["sweep",	"swept",	"swept",	"sweeps",	"sweeping",	"barrer/arrastrar",			"Mover de un lado a otro"],
	["meet",	"met",		"met",		"meets",	"meeting",	"conocer/quedar/verse/buscar",		"Ir a buscar, quedar verse, quedar(con)"],
	["lead",	"led",		"led",		"leads",	"leading",	"dirigir/liderar/guiar/conducir/llevar","Ir ganando"],
	["leap",	"leaped/leapt",	"leaped/leapt",	"leaps",	"leaping",	"salto/saltar",				"Salto horizotal, Jump hacia arriba"],
	["deal",	"dealt",	"dealt",	"deals",	"dealing",	"repartir/encargarse/negociar",		""],
	["lean",	"leaned/leant","leaned/leant",	"leans",	"leaning",	"recargar/apoyar/inclinar/apoyarse/ladear","Recargarse en algo, un sillón"],
	["sleep",	"slept",	"slept",	"sleeps",	"sleeping",	"dormir",				""],
	["weep",	"wept",		"wept",		"weeps",	"weeping",	"sollozar/llorar",			""],
	["feel",	"felt",		"felt",		"feels",	"feeling",	"sentir",				""],
	["kneel",	"kneeled/knelt","kneeled/knelt","kneels",	"kneeling",	"arrodillar/arrodillarse",		""],
	["feed",	"fed",		"fed",		"feeds",	"feeding",	"alimentar/comer/alimentarse",		""],
	["bleed",	"bled",		"bled",		"bleeds",	"bleeding",	"sangrar/desangrar/purgar",		""],
	["breed",	"bred",		"bred",		"breeds",	"breeding",	"criar/reproducir/crear",		"Criar a otros animales"],
	["speed",	"speeded/sped",	"speeded/sped",	"speeds",	"speeding",	"acelerar/apresurar/rapidez",		"Ir muy rápido"],
	["mean",	"meant",	"meant",	"means",	"meaning",	"significar/querer/implicar", 		""],
	["dream",	"dreamed/dreamt","dreamed/dreamt","dreams",	"dreaming",	"soñar/imaginar",			""],
	["read",	"read",		"read",		"reads",	"reading",	"leer",					""],
	["hear",	"heard",	"heard",	"hears",	"hearing",	"oir/escuchar",				""],
	["learn",	"learned/learnt","learned/learnt","learns",	"learning",	"aprender/saber/enterarse",		""],
	///
	["find",	"found",	"found",	"finds",	"finding",	"encontrar/hallar/descubrir",		""],
	["bind",	"bound",	"bound",	"binds",	"binding",	"unir/atar/amarrar/encuadernar",	""],
	["grind",	"ground",	"ground",	"grinds",	"grinding",	"moler/triturar/rechinar",		""],
	["wind",	"winded/wound",	"winded/wound",	"winds",	"winding",	"darcuerda/enrollar/arrollar",		""],
	["unwind",	"unwound",	"unwound",	"unwinds",	"unwinding",	"relajar/descansar/desenrollar",	""],
	["unbind",	"unbound",	"unbound",	"unbinds",	"unbinding",	"desatar/desamarrar",			""],
	["send",	"sent",		"sent",		"sends",	"sending",	"enviar/mandar/transmitir",		""],
	["spend",	"spent",	"spent",	"spends",	"spending",	"pasar/gastar/dedicar",			""],
	["bend",	"bent",		"bent",		"bends",	"bending",	"doblar/inclinar/inclinarse",		""],
	["blend",	"blended",	"blended",	"blends",	"blending",	"mezclar/mezclarse/combinar",		""],
	["lend",	"lent",		"lent",		"lends",	"lending",	"prestar/dar/dejar",			""],
	["sting",	"stung",	"stung",	"stings",	"stinging",	"picar/doler/arder",			""],
	["cling",	"clung",	"clung",	"clings",	"clinging",	"aferrar/aderir/aferrarse/agarrarse",	""],
	["swing",	"swung",	"swung",	"swings",	"swinging",	"balancear/oscilar/mecer/columpiar/mover",""],
	["slink",	"slunk",	"slunk",	"slinks",	"slinking",	"escabullirse/escabullir",		"Moverse sigilosamente"],
	["stick",	"stuck",	"stuck",	"sticks",	"sticking",	"pegar/quedarse/aderir/atascar",	""],
	["dig",		"dug",		"dug",		"digs",		"digging",	"cavar/excavar",			"Mover tierra"],
	["hang",	"hanged/hung",	"hanged/hung",	"hangs",	"hanging",	"colgar/esperar/ahorcar",		""],
	//
	["say",		"said",		"said",		"says",		"saying",	"decir/dar/afirmar",			""],	
	["pay",		"paid",		"paid",		"pays",		"paying",	"pagar/prestar/rendir",			""],
	["lay",		"laid",		"laid",		"lays",		"laying",	"poner/hacer/colocar",			""],
	//["inlay",	"inlaid",	"inlaid",	"inlays",	"inlaying",	"incrustar/embutir",			""],	
	["tell",	"told",		"told",		"tells",	"telling",	"decir/contar/saber",			""],
	["sell",	"sold",		"sold",		"sells",	"selling",	"vender/venderse/convencer",		"Tambien to organize an event"],
	["hold",	"held",		"held",		"holds",	"holding",	"sostener/guardar/celebrar/mantener",	""],
	["behold",	"beheld",	"beheld",	"beholds",	"beholding",	"contemplar/mirar/observar",		""],
	["uphold",	"upheld",	"upheld",	"upholds",	"upholding",	"defender/apoyar/mantener/respetar",	""],
	["stand",	"stood",	"stood",	"stands",	"standing",	"soportar/quedar/estar",		""],
	["understand",	"understood",	"understood",	"understands",	"understanding","entender/comprender/saber",		""],
	["withstand",	"withstood",	"withstood",	"withstands",	"withstanding",	"soportar/resistir/aguantar",		"un puente diseñado para soportar terremotos, ser lo suficientemente fuerte, o no ser cambiado por algo, o oponerse a una persona o cosa con éxito"],
	["lose",	"lost",		"lost",		"loses",	"losing",	"perder/quitar/bajar",			""],
	["shoot",	"shot",		"shot",		"shoots",	"shooting",	"disparar/matar/tirar",			""],
	["bite",	"bit",		"bitten",	"bites",	"biting",	"morder/picar/arrancar",		""],
	["hide",	"hid",		"hidden/hid",	"hides",	"hiding",	"esconder/ocultar/esconderse",		""],
	["slide",	"slid",		"slid",		"slides",	"sliding",	"deslizar/pasar/resbalar",		""],
	//
	["buy",		"bought",	"bought",	"buys",		"buying",	"comprar/invitar/adquirir",		""],
	["bring",	"brought",	"brought",	"brings",	"bringing",	"traer/llevar/poner",			""],
	["think",	"thought",	"thought",	"thinks",	"thinking",	"creer/pensar/parecer",			""],
	["fight",	"fought",	"fought",	"fights",	"fighting",	"luchar/pelear/combatir",		""],
	["teach",	"taught",	"taught",	"teaches",	"teaching",	"enseñar/aprender/impartir",		""],
	["catch",	"caught",	"caught",	"catches",	"catching",	"atrapar/coger/capturar",		""],
	["spit",	"spat",		"spat",		"spits",	"spitting",	"escupir/espetar",			""],
	["have",	"had",		"had",		"has",		"having",	"haber/tener/estar",			""],
	["make",	"made",		"made",		"makes",	"making",	"hacer/tomar/realizar",			""],
	//
	["write",	"wrote",	"written",	"writes",	"writing",	"escribir/redactar/anotar",		""],
	["ride",	"rode",		"ridden",	"rides",	"riding",	"llevar/viajar/montar/ir",		"to travel by sitting on a horse, bicycle, or motorcycle and controlling it"],
	["drive",	"drove",	"driven",	"drives",	"driving",	"conducir/manejar/llevar",		""],
	["rise",	"rose",		"risen",	"rises",	"rising",	"aumentar/subir/levantar/ascender/crecer/elevar",		""],
	["strive",	"strove",	"striven",	"strives",	"striving",	"esforzar/esforzarse/luchar",		""],
	["stride",	"strode",	"stridden",	"strides",	"striding",	"zancada/paso/pasar",			"Dar zancada"],
//	["smite",	"smote",	"smitten",	"smites",	"smiting",	"golpear/castigar/aniquilar",		""],
	["speak",	"spoke",	"spoken",	"speaks",	"speaking",	"hablar/decir/intervenir",		""],
	["steal",	"stole",	"stolen",	"steals",	"stealing",	"robar/robarse/quitar",			""],
	["break",	"broke",	"broken",	"breaks",	"breaking",	"romper/quebrar/terminar",		""],
	["wake",	"woke/waked",	"woken/waked",	"wakes",	"waking",	"despertar/levantar",			""],
	["begin",	"began",	"begun",	"begins",	"beginning",	"comenzar/empezar/iniciar",		""],
	["drink",	"drank",	"drunk",	"drinks",	"drinking",	"tomar/brindar/beberse",		""],
	["sink",	"sank",		"sunk",		"sinks",	"sinking",	"hundir/hundirse/descender/caer",	""],
	["stink",	"stank",	"stunk",	"stinks",	"stinking",	"apestar/olermal",			""],
	["swim",	"swam",		"swum",		"swims",	"swimming",	"nadar/bañar/bañarse",			""],
	["spring",	"sprang",	"sprung",	"springs",	"springing",	"saltar/brotar/soltar",			"to jump or move somewhere suddenly"],	
	["wear",	"wore",		"worn",		"wears",	"wearing",	"usar/llevar/poner/vestir",		""],
	["swear",	"swore",	"sworn",	"swears",	"swearing",	"jurar/prometer/maldecir",	""],
	["bear",	"bore",		"borne",	"bears",	"bearing",	"soportar/aguantar/resistir",	"to accept someone or something bad"],
	["tear",	"tore",		"torn",		"tears",	"tearing",	"arrancar/romper/desgarrar/rasgar",	"Debatirse entre algo y algo, to pull paper, cloth, etc. into pieces, or to make a hole in it by accident"],
	//
	["take",	"took",		"taken",	"takes",	"taking",	"tomar/llevar/adoptar",		""],
//	["undertake",	"undertook",	"undertaken",	"undertakes",	"undertaking",	"realizar/emprender/adoptar",	""],
//	["partake",	"partook",	"partaken",	"partakes",	"partaking",	"participar/compartir/tomarparte",""],
	["shake",	"shook",	"shaken",	"shakes",	"shaking",	"sacudir/agitar/mover/menear",	""],
	["get",		"got",		"got/gotten",	"gets",		"getting",	"conseguir/tener/llegar/obtener",	""],
	["forget",	"forgot",	"forgotten",	"forgets",	"forgetting",	"olvidar/olvidarse/perdonar",	""],
	["give",	"gave",		"given",	"gives",	"giving",	"dar/hacer/prestar",		""],
	["forgive",	"forgave",	"forgiven",	"forgives",	"forgiving",	"perdonar/disculpar/olvidar",	""],
	["forbid",	"forbade/forbad","forbidden",	"forbids",	"forbidding",	"prohibir/impedir",		""],
	["shrink",	"shrank",	"shrunk",	"shrinks",	"shrinking",	"reducir/encoger/disminuir",	""],
	["ring",	"rang",		"rung",		"rings",	"ringing",	"sonar/llamar/tocar",		"Llamar por telefono"],
	["run",		"ran",		"run",		"runs",		"running",	"correr/huir/dirigir",		""],
	["know",	"knew",		"known",	"knows",	"knowing",	"saber/conocer/entender",	""],
	["grow",	"grew",		"grown",	"grows",	"growing",	"crecer/cultivar/aumentar",	""],
	["throw",	"threw",	"thrown",	"throws",	"throwing",	"tirar/lanzar/echar",		""],
	["blow",	"blew",		"blown",	"blows",	"blowing",	"soplar/volar/explotar",	""],
	["draw",	"drew",		"drawn",	"draws",	"drawing",	"dibujar/sacar/extraer",	""],
	["withdraw",	"withdrew",	"withdrawn",	"withdraws",	"withdrawing",	"retirar/retirarse/extraer",	"to remove something, especially because of an official decision, He has threatened to withdraw his support, dinero del banco"],
//	["overdraw",	"overdrew",	"overdrawn",	"overdraws",	"overdrawing",	"",				""],
	["fly",		"flew",		"flown",	"flies",	"flying",	"volar/pilotar/viajar",		""],

	["come",	"came",		"come",		"comes",	"coming",	"venir/llegar/ir",		""],
	["overdo",	"overdid",	"overdone",	"overdoes",	"overdoing",	"exagerar/abusar/excederse",	""],
	["undo",	"undid",	"undone",	"undoes",	"undoing",	"deshacer/reparar/anular",	""],
	["go",		"went",		"gone",		"goes",		"going",	"ir/irse/salir",		""],
	["do",		"did",		"done",		"does",		"doing",	"hacer/ver/ser",		""],
	["oversee",	"oversaw",	"overseen",	"oversees",	"overseeing",	"supervisar/vigilar/velar",	""],
	["see",		"saw",		"seen",		"sees",		"seeing",	"ver/mirar/saber",		""],
	["overcome",	"overcame",	"overcome",	"overcomes",	"overcoming",	"superar/vencer/resolver",	""],
	["become",	"became",	"become",	"becomes",	"becoming",	"convertir/volver/hacer",	""],
	["undergo",	"underwent",	"undergone",	"undergoes",	"undergoing",	"someter/recibir/sufrir",	"Someterse a, to experience something, especially a change or medical treatment"],
	["eat",		"ate",		"eaten",	"eats",		"eating",	"comer/comerse/cenar",		""],
	["fall",	"fell",		"fallen",	"falls",	"falling",	"caer/quedar/caerse",		""],
	["be",		"was",		"been",		"is",		"being",	"ser/estar/haber",		""],
	["sit",		"sat",		"sat",		"sits",		"sitting",	"",				""],
	["go",		"went",		"gone",		"goes",		"going",	"",				""]
];
